#customhost = "RDS-endpoint"
#customuser = "RDS-username"
#custompass = "RDS-password"
#customdb = "DB-name"
#custombucket = "S3-bucketname"
#customregion = "us-east-1"

customhost = "db1.cruiqa6ogvdx.ap-south-1.rds.amazonaws.com"
customuser = "admin"
custompass = "admin1234567"
customdb = "projdb"
custombucket = "proj-bucket-494273343511"
customregion = "ap-south-1"
