#customhost = "RDS-endpoint"
#customuser = "RDS-username"
#custompass = "RDS-password"
#customdb = "DB-name"
#custombucket = "S3-bucketname"
#customregion = "us-east-1"

customhost = "db1.c1a8umimc7ma.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "admin1234567"
customdb = "projdb"
custombucket = "mugfd494273343511"
customregion = "us-east-1"
